services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: building_mgmt
      POSTGRES_PASSWORD: building_mgmt
      POSTGRES_DB: building_mgmt
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U building_mgmt"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
