# Generated by Django 5.1.1 on 2025-10-22 07:10

import django.core.validators
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='unit',
            name='unique_unit_number_per_building',
        ),
        migrations.AddField(
            model_name='building',
            name='role',
            field=models.CharField(choices=[('TECH_SUPPORT', 'Technical Support'), ('PROPERTY_MANAGER', 'Property Manager'), ('EXTERNAL_CONTRACTOR', 'External Contractor')], default='TECH_SUPPORT', max_length=32),
        ),
        migrations.AlterField(
            model_name='unit',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=32, validators=[django.core.validators.RegexValidator('^\\+?\\d{7,15}$', 'Enter a valid phone number (digits with optional leading +, 7–15 digits).')], verbose_name='Contact phone'),
        ),
        migrations.AddIndex(
            model_name='unit',
            index=models.Index(fields=['building', 'number'], name='core_unit_buildin_dc6512_idx'),
        ),
        migrations.AddConstraint(
            model_name='unit',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('number'), models.F('building'), name='unique_unit_number_ci_per_building'),
        ),
    ]
