# Generated by Django 5.1.1 on 2025-10-27 13:39

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_building_address_alter_building_description_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='unit',
            name='unique_unit_number_ci_per_building',
        ),
        migrations.AddConstraint(
            model_name='unit',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('number'), models.F('building'), name='unique_unit_number_ci_per_building', violation_error_message='Apartment number must be unique within this building.'),
        ),
    ]
