# Generated by Django 5.1.1 on 2025-10-15 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_building_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
