# Generated by Django 5.1.1 on 2025-10-29 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_unit_unique_unit_number_ci_per_building_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='building',
            options={'ordering': ['name', 'id'], 'verbose_name': 'Building', 'verbose_name_plural': 'Buildings'},
        ),
        migrations.AddField(
            model_name='workorder',
            name='mass_assigned',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Mass assigned'),
        ),
    ]
