# Generated by Django 5.1.1 on 2025-10-16 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_unit_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workorder',
            options={},
        ),
        migrations.RemoveField(
            model_name='workorder',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='workorder',
            name='building',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='work_orders', to='core.building'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_orders', to='core.unit'),
        ),
    ]
