# Generated by Django 5.1.1 on 2025-10-30 10:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_building_options_workorder_mass_assigned'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=40)),
                ('level', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('danger', 'Danger')], default='info', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('first_seen_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('snoozed_until', models.DateField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at', '-id'),
                'indexes': [models.Index(fields=['user', 'category'], name='core_notifi_user_id_c596c9_idx'), models.Index(fields=['user', 'acknowledged_at'], name='core_notifi_user_id_ccb3f8_idx'), models.Index(fields=['user', 'snoozed_until'], name='core_notifi_user_id_9d6aa5_idx')],
                'unique_together': {('user', 'key')},
            },
        ),
    ]
