# Generated by Django 5.1.1 on 2025-10-17 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_workorder_options_remove_workorder_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='contact_phone',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Contact'),
        ),
        migrations.AddField(
            model_name='unit',
            name='owner_name',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Unit Owner'),
        ),
    ]
