# Generated by Django 5.1.1 on 2025-11-02 16:49

import core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkOrderAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(help_text='Upload images or documents related to this work order.', upload_to=core.models.work_order_attachment_upload_to, verbose_name='File')),
                ('original_name', models.CharField(editable=False, max_length=255, verbose_name='Original filename')),
                ('content_type', models.CharField(blank=True, editable=False, max_length=255, verbose_name='Content type')),
                ('size', models.PositiveBigIntegerField(default=0, editable=False, verbose_name='Size (bytes)')),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='core.workorder', verbose_name='Work order')),
            ],
            options={
                'verbose_name': 'Work order attachment',
                'verbose_name_plural': 'Work order attachments',
                'ordering': ['-created_at'],
            },
        ),
    ]
