# Generated by Django 5.1.1 on 2025-10-17 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_unit_contact_phone_unit_owner_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='contact_phone',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Contact'),
        ),
        migrations.AddField(
            model_name='building',
            name='owner_name',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Unit Owner'),
        ),
    ]
