# Generated by Django 5.1.1 on 2025-11-18 09:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_workorderattachment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RoleAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('TECHNICIAN', 'Technician'), ('BACKOFFICE', 'Backoffice Employee'), ('ADMINISTRATOR', 'Administrator'), ('AUDITOR', 'Read-only auditor')], max_length=32)),
                ('action', models.CharField(choices=[('role_added', 'Role added'), ('role_removed', 'Role removed'), ('capability_updated', 'Capabilities updated')], max_length=32)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='role_actions', to=settings.AUTH_USER_MODEL)),
                ('building', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.building')),
                ('target_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_audit_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Role audit log entry',
                'verbose_name_plural': 'Role audit log entries',
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='BuildingMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('TECHNICIAN', 'Technician'), ('BACKOFFICE', 'Backoffice Employee'), ('ADMINISTRATOR', 'Administrator'), ('AUDITOR', 'Read-only auditor')], max_length=32)),
                ('capabilities_override', models.JSONField(blank=True, default=dict)),
                ('building', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='core.building')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Building membership',
                'verbose_name_plural': 'Building memberships',
                'ordering': ['user_id', 'building_id', 'role'],
                'indexes': [models.Index(fields=['user', 'building'], name='core_buildi_user_id_4e4024_idx')],
                'unique_together': {('user', 'building', 'role')},
            },
        ),
    ]
