# Generated by Django 5.1.1 on 2025-10-17 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_add_workorder_priority'),
        ('core', '0008_remove_building_contact_phone_and_more'),
    ]

    operations = [
    ]
