# Generated by Django 5.1.1 on 2025-11-18 10:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_seed_initial_memberships'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='awaiting_approval_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_orders_sent_for_approval', to=settings.AUTH_USER_MODEL, verbose_name='Awaiting approval requested by'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='replacement_request_note',
            field=models.TextField(blank=True, verbose_name='Replacement request note'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('IN_PROGRESS', 'In progress'), ('AWAITING_APPROVAL', 'Awaiting approval'), ('DONE', 'Done')], db_index=True, default='OPEN', max_length=20),
        ),
    ]
