# Generated by Django 5.1.1 on 2025-10-17 21:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_merge_20251018_0001'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='building',
            options={},
        ),
        migrations.AlterModelOptions(
            name='unit',
            options={},
        ),
        migrations.AlterModelOptions(
            name='workorder',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterUniqueTogether(
            name='unit',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='unit',
            name='floor',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='unit',
            name='number',
            field=models.PositiveIntegerField(verbose_name='Apartment number'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='building',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_orders', to='core.building'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('in_progress', 'In progress'), ('done', 'Done')], default='open', max_length=20),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AddConstraint(
            model_name='unit',
            constraint=models.UniqueConstraint(fields=('building', 'number'), name='unique_unit_number_per_building'),
        ),
    ]
