# Generated by Django 5.1.1 on 2025-10-20 07:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_backfill_workorder_building'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='archived_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='building',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.building'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.unit'),
        ),
    ]
