# Generated by Django 5.1.1 on 2025-11-18 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_workorderauditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='buildingmembership',
            name='technician_subrole',
            field=models.CharField(blank=True, choices=[('TECH_SUPPORT', 'Technical Support'), ('PROPERTY_MANAGER', 'Property Manager'), ('EXTERNAL_CONTRACTOR', 'External Contractor')], max_length=32, verbose_name='Technician sub-role'),
        ),
    ]
