# Generated by Django 5.1.1 on 2025-10-20 07:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_backfill_workorder_building'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='building',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_orders', to='core.building'),
        ),
    ]
