# Generated by Django 5.1.1 on 2025-12-17 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_workorder_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildingmembership',
            name='role',
            field=models.CharField(choices=[('TECHNICIAN', 'Technician'), ('BACKOFFICE', 'Backoffice Employee'), ('ADMINISTRATOR', 'Administrator')], max_length=32),
        ),
        migrations.AlterField(
            model_name='roleauditlog',
            name='role',
            field=models.CharField(choices=[('TECHNICIAN', 'Technician'), ('BACKOFFICE', 'Backoffice Employee'), ('ADMINISTRATOR', 'Administrator')], max_length=32),
        ),
    ]
