# Generated by Django 5.1.1 on 2025-12-17 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_backfill_workorder_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorderauditlog',
            name='action',
            field=models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('attachments', 'Attachments updated'), ('status_changed', 'Status changed'), ('approval', 'Approval decision'), ('reassigned', 'Reassigned'), ('archived', 'Archived')], max_length=32),
        ),
    ]
