# Generated by Django 5.1.1 on 2025-12-18 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_workorder_approved_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='lawyer_only',
            field=models.BooleanField(db_index=True, default=False, help_text='Only lawyers, backoffice employees, and administrators can view these work orders.', verbose_name='Lawyer-only visibility'),
        ),
        migrations.AlterField(
            model_name='buildingmembership',
            name='role',
            field=models.CharField(choices=[('TECHNICIAN', 'Technician'), ('BACKOFFICE', 'Backoffice Employee'), ('LAWYER', 'Lawyer'), ('ADMINISTRATOR', 'Administrator')], max_length=32),
        ),
        migrations.AlterField(
            model_name='roleauditlog',
            name='role',
            field=models.CharField(choices=[('TECHNICIAN', 'Technician'), ('BACKOFFICE', 'Backoffice Employee'), ('LAWYER', 'Lawyer'), ('ADMINISTRATOR', 'Administrator')], max_length=32),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='building',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_orders', to='core.building', verbose_name='Building'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='deadline',
            field=models.DateField(verbose_name='Deadline'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='priority',
            field=models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], db_index=True, default='MEDIUM', max_length=10, verbose_name='Priority'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_orders', to='core.unit', verbose_name='Unit'),
        ),
    ]
