# Generated by Django 5.1.1 on 2025-12-18 13:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def populate_created_by(apps, schema_editor):
    WorkOrder = apps.get_model("core", "WorkOrder")
    WorkOrderAuditLog = apps.get_model("core", "WorkOrderAuditLog")

    created_entries = (
        WorkOrderAuditLog.objects.filter(
            action="created",
            actor_id__isnull=False,
        )
        .values_list("work_order_id", "actor_id")
    )
    for work_order_id, actor_id in created_entries:
        if not work_order_id or not actor_id:
            continue
        WorkOrder.objects.filter(
            pk=work_order_id,
            created_by__isnull=True,
        ).update(created_by_id=actor_id)


def reverse_populate_created_by(apps, schema_editor):
    # No-op; we do not want to remove creator metadata on downgrade.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_backfill_lawyer_confidential'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_orders_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.RunPython(populate_created_by, reverse_populate_created_by),
    ]
