# Generated by Django 5.1.1 on 2026-02-03 09:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_workorder_created_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TodoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In progress'), ('done', 'Done'), ('archived', 'Archived')], db_index=True, default='pending', max_length=20)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('week_start', models.DateField(db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='todo_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'To-do item',
                'verbose_name_plural': 'To-do items',
                'ordering': ('due_date', 'pk'),
            },
        ),
        migrations.CreateModel(
            name='TodoActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('status_changed', 'Status changed'), ('deleted', 'Deleted')], max_length=32)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='todo_activities', to=settings.AUTH_USER_MODEL)),
                ('todo_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='core.todoitem')),
            ],
            options={
                'verbose_name': 'To-do activity',
                'verbose_name_plural': 'To-do activities',
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='TodoList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('week_start', models.DateField(db_index=True)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='todo_lists', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'To-do list',
                'verbose_name_plural': 'To-do lists',
                'ordering': ('-week_start', '-id'),
            },
        ),
        migrations.AddField(
            model_name='todoitem',
            name='todo_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.todolist'),
        ),
        migrations.AddIndex(
            model_name='todolist',
            index=models.Index(fields=['user', 'week_start'], name='core_todoli_user_id_fc23d5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='todolist',
            unique_together={('user', 'week_start')},
        ),
        migrations.AddIndex(
            model_name='todoitem',
            index=models.Index(fields=['user', 'week_start'], name='core_todoit_user_id_f9daf3_idx'),
        ),
        migrations.AddIndex(
            model_name='todoitem',
            index=models.Index(fields=['user', 'status'], name='core_todoit_user_id_804642_idx'),
        ),
    ]
