# Generated by Django 5.1.1 on 2026-02-03 09:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_todoitem_todoactivity_todolist_todoitem_todo_list_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TodoWeekSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('week_start', models.DateField(db_index=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('completed_at', models.DateTimeField()),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('reopened_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('todo_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='week_snapshots', to='core.todoitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='todo_week_snapshots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Weekly to-do snapshot',
                'verbose_name_plural': 'Weekly to-do snapshots',
                'ordering': ('-week_start', '-completed_at'),
                'indexes': [models.Index(fields=['user', 'week_start'], name='core_todowe_user_id_9c1088_idx'), models.Index(fields=['todo_item', 'week_start'], name='core_todowe_todo_it_b65d91_idx')],
            },
        ),
    ]
