# Generated by Django 5.1.1 on 2026-02-18 09:46

import core.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_workorder_forwarding'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=40, unique=True)),
                ('label', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('requires_receipt', models.BooleanField(default=True)),
                ('max_amount_per_day', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('mileage_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'Expense category',
                'verbose_name_plural': 'Expense categories',
                'ordering': ('label', 'code'),
            },
        ),
        migrations.AlterField(
            model_name='workorder',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('IN_PROGRESS', 'In progress'), ('AWAITING_APPROVAL', 'Очаква одобрение от бекофиса'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('DONE', 'Done')], db_index=True, default='OPEN', max_length=20),
        ),
        migrations.CreateModel(
            name='BudgetRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project_code', models.CharField(blank=True, max_length=120)),
                ('description', models.TextField(blank=True)),
                ('requested_amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('approved_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('spent_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('currency', models.CharField(choices=[('USD', 'USD'), ('EUR', 'EUR'), ('BGN', 'BGN')], default='USD', max_length=8)),
                ('allow_overage', models.BooleanField(default=False)),
                ('allow_post_close_expense', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_review', 'Pending review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('needs_info', 'Needs info'), ('closed', 'Closed')], db_index=True, default='draft', max_length=32)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('feature_flag', models.CharField(blank=True, default='budgets', max_length=64)),
                ('notes', models.TextField(blank=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budget_requests_approved', to=settings.AUTH_USER_MODEL)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_requests', to='core.building')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Budget request',
                'verbose_name_plural': 'Budget requests',
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='BudgetRequestEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(choices=[('status', 'Status changed'), ('approval', 'Approval decision'), ('expense', 'Expense recorded'), ('attachment', 'Attachment activity'), ('comment', 'Comment')], max_length=32)),
                ('notes', models.TextField(blank=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budget_events', to=settings.AUTH_USER_MODEL)),
                ('budget_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='core.budgetrequest')),
            ],
            options={
                'verbose_name': 'Budget event',
                'verbose_name_plural': 'Budget events',
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('logged', 'Logged'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='draft', max_length=20)),
                ('incurred_on', models.DateField(default=django.utils.timezone.localdate)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses_approved', to=settings.AUTH_USER_MODEL)),
                ('budget_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='core.budgetrequest')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses_created', to=settings.AUTH_USER_MODEL)),
                ('expense_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='core.expensecategory')),
            ],
            options={
                'verbose_name': 'Expense',
                'verbose_name_plural': 'Expenses',
                'ordering': ('-incurred_on', '-id'),
            },
        ),
        migrations.CreateModel(
            name='ExpenseAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to=core.models._budget_attachment_upload_to)),
                ('original_name', models.CharField(blank=True, max_length=255)),
                ('mime_type', models.CharField(blank=True, max_length=255)),
                ('size', models.PositiveBigIntegerField(default=0)),
                ('checksum', models.CharField(blank=True, max_length=64)),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='core.expense')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expense_attachments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Expense attachment',
                'verbose_name_plural': 'Expense attachments',
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='BudgetFeatureFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(default='budgets', max_length=64)),
                ('role', models.CharField(blank=True, choices=[('TECHNICIAN', 'Technician'), ('BACKOFFICE', 'Backoffice Employee'), ('LAWYER', 'Lawyer'), ('ADMINISTRATOR', 'Administrator')], max_length=32)),
                ('is_enabled', models.BooleanField(default=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('building', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='budget_feature_flags', to='core.building')),
            ],
            options={
                'verbose_name': 'Budget feature flag',
                'verbose_name_plural': 'Budget feature flags',
                'unique_together': {('key', 'building', 'role')},
            },
        ),
        migrations.AddIndex(
            model_name='budgetrequest',
            index=models.Index(fields=['building', 'status'], name='core_budget_buildin_3bc883_idx'),
        ),
        migrations.AddIndex(
            model_name='budgetrequest',
            index=models.Index(fields=['requester', 'status'], name='core_budget_request_a17b47_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['budget_request', 'status'], name='core_expens_budget__e977e4_idx'),
        ),
    ]
