# Generated by Django 5.1.1 on 2026-02-18 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_expensecategory_alter_workorder_status_budgetrequest_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgetrequest',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD'), ('EUR', 'EUR'), ('BGN', 'BGN')], default='EUR', max_length=8),
        ),
    ]
