# Generated by Django 5.1.1 on 2026-02-18 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_alter_budgetrequest_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgetrequest',
            name='building',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='budget_requests', to='core.building'),
        ),
    ]
