# Generated by Django 5.1.1 on 2026-02-18 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_alter_budgetrequest_building'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetrequest',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
