# Generated by Django 5.1.1 on 2026-02-19 17:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_expense_metadata'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetrequest',
            name='archived_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='budgetrequest',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending_review', 'Pending review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('closed', 'Closed')], db_index=True, default='draft', max_length=32),
        ),
        migrations.AddIndex(
            model_name='budgetrequest',
            index=models.Index(fields=['archived_at', 'requester'], name='core_budget_archive_4ade9a_idx'),
        ),
    ]
