# Generated by Django 5.1.1 on 2026-03-20 12:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_budgetrequest_archived_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='workorder',
            index=models.Index(fields=['building', 'archived_at', 'status', 'deadline'], name='core_wo_building_active_idx'),
        ),
        migrations.AddIndex(
            model_name='workorder',
            index=models.Index(fields=['archived_at', 'status', 'deadline'], name='core_wo_active_deadline_idx'),
        ),
    ]
