# Generated by Django 5.1.1 on 2026-03-25 12:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_workorder_core_wo_building_active_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buildings', to=settings.AUTH_USER_MODEL, verbose_name='Отговорник'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('IN_PROGRESS', 'In progress'), ('AWAITING_APPROVAL', 'Awaiting backoffice approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('DONE', 'Done')], db_index=True, default='OPEN', max_length=20),
        ),
    ]
