# Generated by Django 5.1.1 on 2026-03-26 09:11

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_alter_building_owner_alter_workorder_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorderattachment',
            name='thumbnail',
            field=models.FileField(blank=True, editable=False, upload_to=core.models.work_order_attachment_thumbnail_upload_to, verbose_name='Thumbnail'),
        ),
        migrations.AddField(
            model_name='workorderattachment',
            name='thumbnail_height',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True, verbose_name='Thumbnail height'),
        ),
        migrations.AddField(
            model_name='workorderattachment',
            name='thumbnail_width',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True, verbose_name='Thumbnail width'),
        ),
    ]
